subscription_id        = ""
location               = "East US"
resource_group_name    = "groupg-rg-0111"
app_service_plan_name  = "groupg-plan-011"
web_app_name           = "groupg-webapp-mv011"
storage_account_name   = "groupgstmv011"
app_insights_name      = "groupg-insights-mv011"